server:
  port: 0

spring:
  application:
    name: admin-service

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka