server:
  port: 0

spring:
  application:
    name: product-service

  datasource:
    url: jdbc:postgresql://localhost:5432/products-db
    username: ${SAROS_DB_USERNAME}
    password: ${SAROS_DB_PASSWORD}

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
#
#  config:
#    import: configserver:http://localhost:8888

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka