server:
  port: 8888

spring:
  application:
    name: spring-cloud-config-server

  cloud:
    config:
      server:
        git:
          default-label: master
          uri: https://github.com/perfectInt/saros-configuration